-- ==============================================================================
-- Portfolio Project: Customer Shopping Behavior Analysis
-- Tech Stack: Python (ETL/EDA) + SQL (Business Insights) + Power BI / Dashboard
-- Dataset: 3,900 Customer Transactions (18+ Features)
-- Database Table: customer
-- ==============================================================================

-- Q1. What is the total revenue generated by male vs. female customers?
-- Business Purpose: Identify the revenue contribution across gender segments to optimize marketing spend.
SELECT 
    gender, 
    SUM(purchase_amount) AS revenue,
    COUNT(customer_id) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value
FROM customer
GROUP BY gender
ORDER BY revenue DESC;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
-- Business Purpose: Identify "Smart Shoppers" / high-value customers who take advantage of promotions while maintaining high basket size.
SELECT 
    customer_id, 
    gender,
    category,
    item_purchased,
    purchase_amount 
FROM customer 
WHERE discount_applied = 'Yes' 
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
ORDER BY purchase_amount DESC;


-- Q3. Which are the top 5 products with the highest average review rating?
-- Business Purpose: Detect flagship customer favorites and quality leaders to feature in promotional campaigns.
SELECT 
    item_purchased, 
    category,
    ROUND(AVG(review_rating), 2) AS avg_product_rating,
    COUNT(customer_id) AS total_reviews
FROM customer
GROUP BY item_purchased, category
ORDER BY avg_product_rating DESC, total_reviews DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
-- Business Purpose: Determine if express shipping customers demonstrate higher purchase willingness / urgency.
SELECT 
    shipping_type, 
    COUNT(customer_id) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--     between subscribers and non-subscribers.
-- Business Purpose: Quantify the financial impact of the subscription program and assess customer lifetime value (LTV).
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(100.0 * COUNT(customer_id) / (SELECT COUNT(*) FROM customer), 2) AS customer_share_pct,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    ROUND(100.0 * SUM(purchase_amount) / (SELECT SUM(purchase_amount) FROM customer), 2) AS revenue_share_pct
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- Business Purpose: Detect products that might be overly discount-dependent or price-sensitive.
SELECT 
    item_purchased,
    category,
    COUNT(*) AS total_sales,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discounted_sales,
    ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate_pct
FROM customer
GROUP BY item_purchased, category
ORDER BY discount_rate_pct DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total 
--     number of previous purchases, and show the count of each segment. 
-- Business Purpose: Understand customer lifecycle distribution to guide retention vs acquisition strategies.
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        purchase_amount,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS number_of_customers,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM customer), 2) AS segment_percentage,
    ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer_type 
GROUP BY customer_segment
ORDER BY number_of_customers DESC;


-- Q8. What are the top 3 most purchased products within each category? 
-- Business Purpose: Use window functions to identify category leaders for inventory and merchandising optimization.
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        SUM(purchase_amount) AS category_product_revenue,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category, 
    item_purchased, 
    total_orders,
    category_product_revenue
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- Business Purpose: Assess whether higher purchasing frequency correlates with subscription adoption to target upsells.
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers,
    ROUND(100.0 * COUNT(customer_id) / (SELECT COUNT(*) FROM customer WHERE previous_purchases > 5), 2) AS pct_of_repeat_buyers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group? 
-- Business Purpose: Identify the demographic powerhouses to tailor messaging, product lines, and ad creatives.
SELECT 
    age_group,
    COUNT(customer_id) AS total_customers,
    SUM(purchase_amount) AS total_revenue,
    ROUND(100.0 * SUM(purchase_amount) / (SELECT SUM(purchase_amount) FROM customer), 2) AS revenue_share_pct,
    ROUND(AVG(purchase_amount), 2) AS avg_order_value
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
